server:
  port: 9988

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=OMSQLDB;encrypt=false
    username: OM_USER
    password: OMSQL@2004
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    properties:
      dialect: "org.hibernate.dialect.SQLServer2012Dialect"

office-forms:
  company: Optical Gallery
  company-address: 446 Myrtle Ave
  company-city: Brooklyn
  company-state: NY
  company-zip: 11205
  company-phone: (718) 246-2020
  commission-rate: 20
  office-forms:
  entry-prompt: EN

  document-folder: o:/edocuments/
  document-local-folder: c:/officemate/data/edocuments/
  mappings:
    192.168.1.152: 192.168.1.168
    192.168.1.153: 192.168.1.163

scheduler:
  user: user123
  pwd: password123
  white-list: 
  - 18.189.210.54
  - 185.183.92.88
  - 67.81.99.20
  - 47.18.222.248
  - 127.0.0.1
  - 0:0:0:0:0:0:0:1

  providers: 3,53
  insurances:
    - Aetna,83
    - Affinity,99
    - Amerigroup Community Plan,82
    - Avesis Vision,112
    - BLOCK VISION,106
    - Cigna,103
    - CIGNA HEALTH AND LIFE INSURANCE,92
    - CPS OPTICAL,107
    - CSA Welfare Fund,101
    - DAVISVISION,94
    - DAVISVISION 32BJ,87
    - Empire Blue Cross Blue Shield,81
    - EMPIRE BLUECROSS BLUESHIELD,89
    - EyeMed,96
    - FIDELIS CARE,85
    - GHI - NY (Group Health, Inc.) ,80
    - HEALTH FIRST,108
    - HEALTH FIRST/ MEDICARE,84
    - HEALTH FIRST/Davis Vision ,93
    - HealthCare Partners, IPA,102
    - HEALTHPLUS/ AMERIGROUP,91
    - Hip - Health Plan Of New York,79
    - HUMANA,111
    - Local 1199,1
    - LOCAL1180 CWA,65
    - LOCAL1199 GREATER NY FUND,67
    - LOCAL1199 NATIONAL BENEFIT FUND,66
    - LOCAL237 teamsters active/retire,31
    - LOCAL3487-S,38
    - LOCAL371 SOCIAL SERVICE ,41
    - LOCAL389 DISTRICT COUNCIL,42
    - MAGNACARE,105
    - Metroplus Health Plan,78
    - National Government Services,77
    - NATIONAL VISION ADMINISTRATORS,104
    - New York Medicaid,98
    - Oxford Helath Plans,76
    - SELF PAY,110
    - Spectera,100
    - UFT,97
    - United Healthcare,75
    - VISION BENEFITS OF AMERICA,109
    - VSP ,95
    - VSP /GUARDIAN ANYTIME.COM,86
    - WellCare Health Plans, Inc,90

  allowed-phones:
 
  topic-incoming: arn:aws:sns:us-east-1:622853243487:topic1

aws:
  sqs:
    reply-queue-url: https://sqs.us-east-1.amazonaws.com/622853243487/sns-reply-queue
    # reply-queue-url:
  connect:
    instanceId: fe126881-6f74-4414-b589-a7e8400c1d55
    contactFlowId: 2b2722d4-59b7-4271-8c19-e4f48f520375
    queueId: a3a2d0e9-90cd-48ff-b82b-714b09fa3721
